- lib/rubyXL/objects/workbook.rb
- spec/lib/cell_spec.rb
The existing 1900 leap year bug fix introduced a off-by-one bug on dates between Jan 1st 1900 and March 1st 1900. This resolves that
> fix date parsing off-by-one on days pre march 1st 1900

- lib/rubyXL/cell.rb
- spec/lib/cell_spec.rb
This will mean that BigDecimal objects are treated the same as other numeric objects.
> Make the cell’s datatype nil when setting a BigDecimal.

- lib/rubyXL/objects/theme.rb
For one of my excel file I have been receiving the following error
```
Unknown child node [a:path] for element [pathLst]
```
As per schemacentral.com link http://www.schemacentral.com/sc/ooxml/e-a_path-2.html , the element name should be `a:path` instead `a:cxn`. This PR fixes the issue.
> Fix the wrong element naming from a:cxn to a:path

- README.rdoc
Hello I'm newbie rubyXL.
Fix following error in readme.rdoc.
```
cell.border_top
NoMethodError: undefined method `border_top' for #<RubyXL::Cell(0,0): nil, datatype=nil, style_index=2>
```
> Fix border example

- README.rdoc
- lib/rubyXL/convenience_methods.rb
- lib/rubyXL/objects/border.rb
- spec/lib/cell_spec.rb
This PR lets people change the color of cell borders. I added convenience methods for coloring column/row borders, explained them in the README, and added specs.
Here's how you can sample it:
```ruby
row_index = 0
[:top, :bottom, :left, :right].each do |dir|
sheet.change_row_border(row_index, dir, 'thin')
sheet.change_row_border_color(row_index, dir, 'ff0000')
end
```
That should give the first row in a spreadsheet a bright red border.
Let me know if you have any questions or suggestions for how to improve this. Thanks!
> Add methods to allow changing the border color of cells

- lib/rubyXL/worksheet.rb
This patch fixes a major performance issue with Worksheet. Every time a new column is added, rubyXL checks if the worksheet is included in the workbook. Unfortunately, it uses `include?` (which ultimately calls `==`) method, which compares every column of every row to see if the worksheets are the same.
This patch fixed this issue by comparing worksheets by reference, which improved performance significantly.
From Ruby documentation:
> Unlike ==, the equal? method should never be overridden by subclasses as it is used to determine object identity (that is, a.equal?(b) if and only if a is the same object as b):
Test used:
```ruby
val = 'a' * 50
workbook = RubyXL::Workbook.new
(1..5).each do |sheet|
worksheet = workbook["Sheet#{sheet}"] || workbook.add_worksheet("Sheet#{sheet}") …
```
> Improve performance of add_cell by fixing workbook validation (10-40x improvement)

- lib/rubyXL/convenience_methods.rb
It seems like invoking `change_border` doesn't apply a border cell style to generated excel after `2817018d57fd0ccb5a1c4d52b75950ba71671fac` was committed.
This PR fixed it but I'm not sure how to test it accurately.
Thanks!
> Fix bug in `modify_border` to show border of cell

- lib/rubyXL/objects/text.rb
- spec/lib/text_spec.rb
This fixes a bug in the regular expression for escaping invalid XML characters.
Ruby requires the special syntax `\u{hex}` for matching unicode character with more than 4 bytes.
Because of this the regex range `[^\u10000-\u10FFFF]` was interpreted as `[^\u1000]|[^0-\u10FF]|[^FF]`.
I found this bug because `RUBYOPT=-W3` triggered a duplicate character range warning for the regex.
> Fix invalid XML escaping of U+10000 to U+10FFFF character range

- lib/rubyXL/objects/sheet_data.rb
- spec/lib/cell_spec.rb
Cell `value` for `inlineStr` cells was always `nil`. Here is a small change to make `value` return the string contents of such cells.
Example for a spreadsheet with an `inlineStr` cell:
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<sheetData>
<row r="1">
<c r="A1" t="inlineStr">
<is>
<t>Hello</t>
</is>
</c>
</row>
</sheetData>
</worksheet>
I am not sure on how to properly generate the XML structure for the spec, so I'll gladly adjust if there is a better way. :)
> Support inlineStr cells

- lib/rubyXL/objects/connection.rb
- lib/rubyXL/objects/query_table.rb
- lib/rubyXL/objects/simple_types.rb
- lib/rubyXL/objects/workbook.rb
- lib/rubyXL/objects/worksheet.rb
I have a need to read/write XLSM files which make use of QueryTable and Connections. I wanted to add support for these structures to RubyXL and ensure that references are not broken on write, thus corrupting the output file. 
I am not 100% sure if what I have done is correct, please let me know if there is something wrong or missing. The below changes do now allow me to read and write files containing these entities.
> Adding support for QueryTable and external Connections

- lib/rubyXL/objects/document_properties.rb
Excel shows up a warning when `xsi:type="dcterms:W3CDTF"` is set in docProps/core.xml on `dc:creator` or `cp:lastModifiedBy`.
> Avoid warning after setting creator or modifier when opening in excel

- rubyXL.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/rubyXL or some tools or APIs that use the gem's metadata.
> GitHub is HTTPS by default

- lib/rubyXL/convenience_methods/workbook.rb
- spec/lib/workbook_spec.rb
As I mentioned here https://github.com/weshatheleopard/rubyXL/issues/395 before, I made a convenience method for the workbook title property.
To see the value: `workbook.title`
To set the value: `workbook.title = 'TITLE'`
Please review my code.
Best,
> Add convinience methods for set and get workbook title property

- lib/rubyXL/convenience_methods/cell.rb
- spec/lib/cell_spec.rb
This PR is to execute date_to_num when the data is Time.
```
cell = book[0].add_cell(0,0,'')
cell.set_number_format('ddd mmm dd, yyyy HH:MM:SS')
cell.change_contents(Time.new)
cell.datatype
=> "str"
```
at excel
```
2022-02-23 13:42:46 +0900
```
```
...
cell = book[0].add_cell(0,0,'')
cell.set_number_format('ddd mmm dd, yyyy HH:MM:SS')
cell.change_contents(Time.new)
cell.datatype
=> nil
```
at excel
```
Wed Feb 23, 2022 04:38:40
```
> execute date_to_num when the data is Time

- CHANGELOG.md
This PR adds a changelog covering the changes in the two most recent versions of the gem.
It'd be great to have (and keep updated!) a file like this in the repo, as it makes it much easier to work out what's relevant when you're keeping your dependencies up to date. Tools like GitHub's Dependabot automatically show what's in the changelog to make it super easy 🧈
> Add a `CHANGELOG.md` and describe the last two versions of the gem

- rubyXL.gemspec
I noticed that http://github.com/gilt/rubyXL redirects to https://github.com/weshatheleopard/rubyXL, so replaced it.
This URL is used at the following part of https://rubygems.org/gems/rubyXL
> Improve gem homepage URL

- lib/rubyXL/objects/external_links.rb
This should fix #435 by adding support for the alternateUrls element ocurring in some newer excel files.
---
The program was tested solely for our own use cases, which might differ from yours.
Florian Pfitzer <florian.pfitzer@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)
Licensed under MIT License
> add support for alternateUrls OOXML

- rubyXL.gemspec
I was surprised to find dozens of security vulnerability warnings for my application. The offending dependencies were: git, rack, nokogiri, stringio, and rdoc. The offending versions didn't make sense because my application is kept up-to-date and we're running the latest known-security versions of these, and we don't even use the git gem.
Upon closer inspection I realised that these were all coming from `bundle/gems/rubyXL-3.4.22/Gemfile.lock`.
Now, this is a false positive with our vulnerability scanner, but it expects that there's only one `Gemfile.lock` file for an application which is a reasonable assumption.
There's no reason to ship `Gemfile.lock`. Applications won't use it. I don't think there's even a reason to have `Gemfile.lock` committed to the repo here at all, but that's up …
> chore(gemspec): don't include Gemfile.lock

- lib/rubyXL/worksheet.rb
- spec/lib/cell_spec.rb
Microsoft Excel has a limit of 32767 characters for cell content.
In the current version of RubyXL, writing content in a cell that exceeds the limit will simply generate a broken book. "broken" means that Excel says it found unreadable content.
Reproducing code:
```
require 'rubyXL'
bad_data = 'A' * 32768
workbook = RubyXL::Workbook.new
workbook[0].add_cell(0,0,bad_data)
workbook.write('broken_book.xlsx') # Broken book for MS Excel will be saved.
```
So I added raising exception to Worksheet#add_cell when it is passed too long contents.
I also wrote a test related to this.
However, how Worksheet#add_cell behaves when too long content is passed may be discussed. For example: instead of throwing an exception, truncate the content beyond the limit and add it to the cell.
> Prevent too long cell contents from breaking Excel book

- lib/rubyXL/convenience_methods/workbook.rb
- spec/lib/cell_spec.rb
First of all, thank you for creating this awesome gem !
I encountered a case where change_border_color changes the border color of other cells with the same style.
Steps to reproduce are
```ruby
require 'bundler/inline'
gemfile(true) do
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem "rubyXL", github: 'weshatheleopard/rubyXL', branch: 'master'
gem 'minitest'
end
require 'rubyXL'
require 'rubyXL/convenience_methods'
require 'minitest/autorun'
class ChangeBorderTest < Minitest::Test
def setup
workbook = RubyXL::Workbook.new
worksheet = workbook[0]
worksheet.add_cell(0, 0)
worksheet.add_cell(0, 1)
@cell = worksheet[0][0]
@another_cell = worksheet[0][1]
@cell.change_border(:right, 'thick')
@another_cell.change_border(:right, 'thick') …
```
> `change_border_color` modifies the border color of other cells.
